insert into department (department_name) values ('FINANCE');
insert into department (department_name) values ('HR AND ADMIN');
insert into department (department_name) values ('MARKETING AND SALES');
insert into department (department_name) values ('MANUAL JOB DELIVERY');
insert into department (department_name) values ('TRAINING AND CONTENT');
insert into department (department_name) values ('COMPLIANCE SUPPORT');
insert into department (department_name) values ('ONBOARDING SUPPORT');
insert into department (department_name) values ('PROGRAMMATIC SUPPORT');
insert into department (department_name) values ('POSTING SUPPORT');
insert into department (department_name) values ('TECHNICAL SUPPORT');
insert into department (department_name) values ('SOURCING');
insert into department (department_name) values ('PRODUCT DESIGN');
insert into department (department_name) values ('INFORMATION TECHNOLOGY');
insert into department (department_name) values ('QUALITY ASSURANCE');
insert into department (department_name) values ('SOFTWARE DEVELOPMENT');

insert into team (team_name) values ('COMPLIANCE SUPPORT');
insert into team (team_name) values ('CORPORATE');
insert into team (team_name) values ('CUSTOMER SUPPORT');
insert into team (team_name) values ('DATA ANALYST');
insert into team (team_name) values ('FINANCE');
insert into team (team_name) values ('HUMAN RESOURCE AND ADMIN');
insert into team (team_name) values ('INFORMATION TECHNOLOGY');
insert into team (team_name) values ('INTERNAL SOURCING');
insert into team (team_name) values ('IT BIZOPS TEAM');
insert into team (team_name) values ('IT HELPDESK TEAM');
insert into team (team_name) values ('IT OPERATIONS,HELPDESK TEAM');
insert into team (team_name) values ('IT SYSOPS TEAM');
insert into team (team_name) values ('MANUAL JOB DELIVERY');
insert into team (team_name) values ('MARKETING AND SALES');
insert into team (team_name) values ('ONBOARDING SUPPORT');
insert into team (team_name) values ('OPERATIONS');
insert into team (team_name) values ('OTHER SOFTWARE DEV');
insert into team (team_name) values ('POSTING SUPPORT');
insert into team (team_name) values ('PRODUCT DESIGN');
insert into team (team_name) values ('PROGRAMMATIC SUPPORT');
insert into team (team_name) values ('QUALITY ASSURANCE');
insert into team (team_name) values ('SOFTWARE DEV TEAM 1');
insert into team (team_name) values ('SOFTWARE DEV TEAM 2');
insert into team (team_name) values ('SOFTWARE DEVELOPMENT');
insert into team (team_name) values ('TECHNICAL SUPPORT');
insert into team (team_name) values ('TRAINING AND CONTENT');
insert into team (team_name) values ('TRIAGE TEAM');
