GET http://localhost:8000/api/employee HTTP/1.1 content-type: application/json

###

GET http://localhost:8000/api/team HTTP/1.1 content-type: application/json

### get departments information

GET http://localhost:8000/api/departments HTTP/1.1
content-type: application/json

### add employee
POST http://localhost:8000/api/employee HTTP/1.1 
content-type: application/json

{
    "first_name": "Brian",
    "last_name": "Lisondra",
    "middle_name": "Garcia",
    "email": "brian@gmail.com",
    "birth_date": "12/12/2001",
    "gender": "M",
    "address": "Talamban Cebu",
    "mobile_number": "09154156111",
    "password": "pass123",
    "status": "active",
    "shift_schedule": "A",
    "work_type": 0,
    "PTO": 0,
    "holiday_off": 0,
    "location": 0
}

### add employee into team 
POST http://localhost:8000/api/team/55 HTTP/1.1 
content-type: application/json

{
    "department_id": 1,
    "employee_id": 6    
}

### add teamlead 
POST http://localhost:8000/api/teamlead HTTP/1.1 
content-type: application/json

{
    "first_name": "TL Lebron",
    "last_name": "James",
    "middle_name": "Lisondra",
    "email": "lebron@gmail.com",
    "birth_date": "10/12/2001",
    "gender": "M",
    "address": "Talamban Cebu",
    "mobile_number": "09154156111",
    "password": "pass123",
    "department_id": 1,    
    "team_id": 55
}