GET http://localhost:8000/api/employee/6 HTTP/1.1
content-type: application/json

###

GET http://localhost:8000/api/team HTTP/1.1 content-type: application/json

### get departments information

GET http://localhost:8000/api/departments HTTP/1.1
content-type: application/json

### get admin master page

GET http://localhost:8000/api/admin/masterpage HTTP/1.1
content-type: application/json

### get all users

GET http://localhost:8000/api/users HTTP/1.1
content-type: application/json

### get teamlead

GET http://localhost:8000/api/teamlead/5 HTTP/1.1
content-type: application/json



### add employee
POST http://localhost:8000/api/employee HTTP/1.1
content-type: application/json

{
    "first_name": "Anotherpne",
    "last_name": "tesdtsat",
    "middle_name": "Hulk",
    "email": "hahah@gmail.com",
    "birth_date": "11/12/2001",
    "gender": "M",
    "address": "Cebu",
    "mobile_number": "09154156111",
    "password": "pass123",
    "status": "active",
    "department_id": 2,
    "team_id": 57
}

### add employee into team 
POST http://localhost:8000/api/team/55 HTTP/1.1 
content-type: application/json

{
    "department_id": 1,
    "employee_id": 6    
}

### add attendance 
POST http://localhost:8000/api/attendance/6 HTTP/1.1 
content-type: application/json

### add attendance 
GET http://localhost:8000/api/attendance/6 HTTP/1.1 
content-type: application/json



### add teamlead 
POST http://localhost:8000/api/teamlead HTTP/1.1 
content-type: application/json

{
    "first_name": "TL Kobe",
    "last_name": "James",
    "middle_name": "Lisondra",
    "email": "lebron@gmail.com",
    "birth_date": "10/12/2001",
    "gender": "M",
    "address": "Talamban Cebu",
    "mobile_number": "09154156111",
    "password": "pass123",
    "department_id": 2,    
    "team_id": 57
}

### add admin 
POST http://localhost:8000/api/admin HTTP/1.1 
content-type: application/json

{
   
    "email": "Kyire@gmail.com",
    "password": "pass123"
}